import { GenerationResult } from '@/types'

export type ProjectFile = {
  path: string
  content: string
}

function slugify(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'simplyui-project'
}

function escapeString(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

export function createNextProjectFiles(result: GenerationResult, projectName?: string): ProjectFile[] {
  const name = projectName || result.userPrompt.slice(0, 48) || 'SimplyUI Project'
  const slug = slugify(name)
  const components = result.generation.componentList

  return [
    {
      path: 'README.md',
      content: `# ${name}

Generated by SimplyUI.

## What is included
- Next.js app router project
- TypeScript setup
- Reusable local UI component library
- Generated feature component
- Professional CSS foundation
- ZIP-ready folder structure

## Run locally
\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000.
`,
    },
    {
      path: 'package.json',
      content: JSON.stringify({
        name: slug,
        version: '1.0.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '^16.1.6',
          react: '^19.2.3',
          'react-dom': '^19.2.3',
        },
        devDependencies: {
          '@types/node': '^20.17.10',
          '@types/react': '^19.0.2',
          '@types/react-dom': '^19.0.2',
          typescript: '^5.7.2',
        },
      }, null, 2),
    },
    {
      path: '.env.example',
      content: 'NEXT_PUBLIC_APP_NAME=SimplyUI Generated Project\n',
    },
    {
      path: 'next.config.ts',
      content: "import type { NextConfig } from 'next'\n\nconst nextConfig: NextConfig = {}\n\nexport default nextConfig\n",
    },
    {
      path: 'tsconfig.json',
      content: JSON.stringify({
        compilerOptions: {
          target: 'ES2020',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          baseUrl: '.',
          paths: { '@/*': ['./*'] },
        },
        include: ['**/*.ts', '**/*.tsx'],
        exclude: ['node_modules'],
      }, null, 2),
    },
    {
      path: 'app/layout.tsx',
      content: `import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${escapeString(name)}',
  description: 'Generated by SimplyUI',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    },
    {
      path: 'app/page.tsx',
      content: `import GeneratedUI from '@/components/generated/GeneratedUI'

export default function HomePage() {
  return <GeneratedUI />
}
`,
    },
    {
      path: 'app/globals.css',
      content: `:root {
  color-scheme: dark;
  --bg: #09090b;
  --panel: rgba(255,255,255,0.04);
  --border: rgba(255,255,255,0.10);
  --text: #f8fafc;
  --muted: #a1a1aa;
  --accent: #10b981;
}

* { box-sizing: border-box; }
html, body { min-height: 100%; }
body {
  margin: 0;
  background:
    radial-gradient(circle at 18% 10%, rgba(16,185,129,.14), transparent 30%),
    radial-gradient(circle at 82% 0%, rgba(59,130,246,.12), transparent 30%),
    var(--bg);
  color: var(--text);
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

button, input, select, textarea { font: inherit; }
a { color: inherit; }
`,
    },
    {
      path: 'components/generated/GeneratedUI.tsx',
      content: result.generation.code,
    },
    {
      path: 'components/ui/index.tsx',
      content: uiLibrary(),
    },
    {
      path: 'lib/project-meta.ts',
      content: `export const projectMeta = {
  name: '${escapeString(name)}',
  prompt: '${escapeString(result.userPrompt)}',
  generatedAt: '${result.timestamp}',
  components: ${JSON.stringify(components, null, 2)},
}
`,
    },
    {
      path: '.github/workflows/ci.yml',
      content: `name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
`,
    },
  ]
}

function uiLibrary() {
  return `'use client'

import React from 'react'

type CommonProps = {
  children?: React.ReactNode
  className?: string
  style?: React.CSSProperties
}

export function Button({ children, variant = 'primary', onClick, style }: CommonProps & { variant?: string; size?: string; onClick?: () => void }) {
  return <button onClick={onClick} style={{ border: 0, borderRadius: 12, padding: '10px 16px', background: variant === 'ghost' ? 'transparent' : 'linear-gradient(135deg,#10b981,#059669)', color: 'white', fontWeight: 800, cursor: 'pointer', ...style }}>{children}</button>
}

export function Card({ title, subtitle, children, style }: CommonProps & { title?: React.ReactNode; subtitle?: React.ReactNode }) {
  return <section style={{ border: '1px solid var(--border)', background: 'var(--panel)', borderRadius: 18, padding: 22, ...style }}>{title && <h2 style={{ margin: 0 }}>{title}</h2>}{subtitle && <p style={{ color: 'var(--muted)' }}>{subtitle}</p>}{children}</section>
}

export function Input({ label, value, onChange, placeholder, type = 'text', style }: { label?: string; value?: string; onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void; placeholder?: string; type?: string; style?: React.CSSProperties }) {
  return <label style={{ display: 'grid', gap: 7, ...style }}>{label && <span style={{ color: 'var(--muted)', fontSize: 13 }}>{label}</span>}<input value={value} onChange={onChange} placeholder={placeholder} type={type} style={{ minHeight: 42, borderRadius: 10, border: '1px solid var(--border)', background: 'rgba(255,255,255,.06)', color: 'var(--text)', padding: '0 12px' }} /></label>
}

export function Table({ columns = [], data = [] }: { columns?: { key: string; header: string }[]; data?: Record<string, React.ReactNode>[]; striped?: boolean }) {
  return <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr>{columns.map((column) => <th key={column.key} style={{ textAlign: 'left', padding: 10, color: 'var(--muted)', borderBottom: '1px solid var(--border)' }}>{column.header}</th>)}</tr></thead><tbody>{data.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column.key} style={{ padding: 10, borderBottom: '1px solid rgba(255,255,255,.06)' }}>{row[column.key]}</td>)}</tr>)}</tbody></table></div>
}

export function Navbar({ brand, items = [], actions = [] }: { brand?: string; items?: { label: string; href?: string }[]; actions?: { label: string; variant?: string }[] }) {
  return <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottom: '1px solid var(--border)' }}><strong>{brand}</strong><div style={{ display: 'flex', gap: 12 }}>{items.map((item) => <a key={item.label} href={item.href || '#'}>{item.label}</a>)}{actions.map((action) => <Button key={action.label} variant={action.variant}>{action.label}</Button>)}</div></nav>
}

export function Badge({ children, label }: CommonProps & { label?: string }) { return <span style={{ display: 'inline-flex', border: '1px solid rgba(16,185,129,.25)', background: 'rgba(16,185,129,.08)', color: '#34d399', borderRadius: 999, padding: '4px 9px', fontSize: 12, fontWeight: 800 }}>{children || label}</span> }
export function Alert({ title, children }: CommonProps & { title?: string; variant?: string }) { return <Card title={title}>{children}</Card> }
export function Avatar({ src, alt, fallback }: { src?: string; alt?: string; fallback?: string }) { return src ? <img src={src} alt={alt || ''} style={{ width: 36, height: 36, borderRadius: '50%' }} /> : <span style={{ width: 36, height: 36, borderRadius: '50%', display: 'grid', placeItems: 'center', background: 'rgba(255,255,255,.08)' }}>{fallback || 'U'}</span> }
export function Progress({ value = 0 }: { value?: number }) { return <div style={{ height: 8, background: 'rgba(255,255,255,.08)', borderRadius: 999 }}><div style={{ width: \`\${value}%\`, height: '100%', background: 'var(--accent)', borderRadius: 999 }} /></div> }
export function Stat({ label, value, trend, subtitle, icon }: { label?: string; value?: React.ReactNode; trend?: { value: string } | string; subtitle?: string; icon?: React.ReactNode }) { return <Card><div>{icon}</div><p style={{ color: 'var(--muted)' }}>{label}</p><strong style={{ fontSize: 28 }}>{value}</strong><p style={{ color: '#34d399' }}>{typeof trend === 'string' ? trend : trend?.value}</p><small>{subtitle}</small></Card> }
export function Chart() { return <div style={{ height: 220, border: '1px solid var(--border)', borderRadius: 14, display: 'grid', placeItems: 'center', color: 'var(--muted)' }}>Chart placeholder</div> }
export function Sidebar({ title, groups = [] }: { title?: string; groups?: { label: string; items: { id: string; label: string }[] }[]; width?: number }) { return <aside style={{ width: 240, padding: 16, borderRight: '1px solid var(--border)' }}><strong>{title}</strong>{groups.map((group) => <div key={group.label}><p>{group.label}</p>{group.items.map((item) => <div key={item.id}>{item.label}</div>)}</div>)}</aside> }
export function Modal({ children }: CommonProps) { return <div>{children}</div> }
export function Toggle({ checked, onChange }: { checked?: boolean; onChange?: (checked: boolean) => void }) { return <input type="checkbox" checked={checked} onChange={(event) => onChange?.(event.target.checked)} /> }
export function Tabs({ tabs = [] }: { tabs?: { label: string; content: React.ReactNode }[] }) { return <div>{tabs.map((tab) => <Card key={tab.label} title={tab.label}>{tab.content}</Card>)}</div> }
export function Divider() { return <hr style={{ borderColor: 'var(--border)' }} /> }
export function Select({ options = [], value, onChange }: { options?: { label: string; value: string }[]; value?: string; onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void }) { return <select value={value} onChange={onChange}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> }
`
}
